app/Http/routes.php
Route::group(['prefix' => 'portal', 'middleware' => 'auth'], function(){

	# Logout Backdoor
	Route::get('logout-backdoor', ['as' => 'logout', 'uses' => 'AuthenticationController@logout']);

	# Popup Activation
	Route::get('information-security', ['as' => 'information_security', 'uses' => 'PopupController@information_security']);
	Route::get('attendance-policy', ['as' => 'attendance_policy', 'uses' => 'PopupController@attendance_policy']);
	Route::get('csr-non-performance-policy', ['as' => 'csr_non_performance_policy', 'uses' => 'PopupController@csr_non_performance_policy']);
	Route::get('code-of-conduct', ['as' => 'code_of_conduct', 'uses' => 'PopupController@code_of_conduct']);
	Route::get('zero-tolerance', ['as' => 'zero_tolerance', 'uses' => 'PopupController@zero_tolerance']);
	Route::get('refresh-policy', ['as' => 'refresh_policy', 'uses' => 'PopupController@refresh_policy']);
	Route::get('my-week-ending-schedule', ['as' => 'my_week_ending_schedule', 'uses' => 'PopupController@my_week_ending_schedule']);
	Route::get('my-shift-schedule', ['as' => 'my_shift_schedule', 'uses' => 'PopupController@my_shift_schedule']);
	Route::get('my-break-schedule-accept/{break_index}', ['as' => 'my_break_schedule_accept', 'uses' => 'PopupController@my_break_schedule_accept']);

	# Dashboard
	Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
	Route::post('dashboard_store', ['as' => 'dashboard_store', 'uses' => 'DashboardController@store']);

	# Profile
	Route::get('profile', ['as' => 'profile', 'uses' => 'ProfileController@index']);

	# Messaging
	Route::group(['prefix' => 'message'], function(){
		# Message Views
		Route::get('inbox', ['as' => 'inbox', 'uses' => 'ConversationController@index']);
		Route::get('messages/{conversation_id?}/{conversation_member_id?}/{_?}', ['as' => 'showmessages', 'uses' => 'ConversationController@messages']);
		Route::get('my-messages', ['as' => 'my_messages', 'uses' => 'ConversationController@my_messages']);
		Route::get('notification', ['as' => 'notification_message', 'uses' => 'ConversationController@notification']);
		
		# Message Forms
		Route::get('compose', ['as' => 'compose_message', 'uses' => 'ConversationController@compose']);
		Route::get('reply/{conversation_id}/{conversation_member_id?}/{_}', ['as' => 'reply_message', 'uses' => 'ConversationController@reply']);
		
		# Message Submits
		Route::post('send-reply', ['as' => 'send_reply_message', 'uses' => 'ConversationController@send_reply']);
		Route::post('send', ['as' => 'send_message', 'uses' => 'ConversationController@send']);
		Route::get('delete/{id}', ['as' => 'delete_message', 'uses' => 'ConversationController@delete']);

		Route::get('user-ldap-search', ['as' => 'user_ldap_search', 'uses' => 'ConversationController@searchldap']);
		Route::get('check-recipient', ['uses' => 'ConversationController@checkreceipient']);
	});
	
	# Payslip Password Reset
	Route::group(['prefix' => 'reset-payslip-password'], function(){
		Route::get('/', ['as' => 'payslip_index', 'uses' => 'PayslipPasswordResetController@index']);
		Route::get('generate', ['as' => 'payslip_generate', 'uses' => 'PayslipPasswordResetController@generate']);
	});

	#	View
	Route::get('avaya-one-x-guide', ['as' => 'avaya_one_x_guide', 'uses' => 'FileUploadsController@avaya_one_x_guide']);
	Route::get('paid-leaves', ['as' => 'paid_leaves', 'uses' => 'FileUploadsController@paid_leaves']);
	Route::get('it-security-policy', ['as' => 'it_security_policy', 'uses' => 'FileUploadsController@it_security_policy']);
	Route::get('qa-newsletter', ['as' => 'qa_newsletter', 'uses' => 'FileUploadsController@qa_newsletter']);

	# Transfer Log
	Route::group(['prefix' => 'transfer-log'], function(){
		Route::get('logger/{account_id?}/{skill_id?}', ['as' => 'transfer_log', 'uses' => 'TransferLogController@index']);
		Route::get('populate-calls', ['as' => 'populate_calls', 'uses' => 'TransferLogController@callsreceiveddropdown']);
		Route::get('populate-extDept', ['as' => 'populate_extension', 'uses' => 'TransferLogController@extdept']);
		Route::post('save-transfer-log', ['as' => 'save_transfer_log', 'uses' => 'TransferLogController@store']);
		Route::get('transfer-log-report', ['as' => 'transfer_log_report', 'uses' => 'TransferLogController@show']);
	});
	
	# Leave
	Route::group(['prefix' => 'leave'], function(){
		# Agent
		Route::group(['prefix' => 'agent'], function(){
			Route::get('/', ['as' => 'leave_agent_index', 'uses' => 'LeaveAgentController@index']);
			Route::get('/filed-leaves', ['as' => 'leave_agent_filed', 'uses' => 'LeaveAgentController@filed_leaves']);
			Route::post('/download-filed-leaves', ['as' => 'leave_agent_download', 'uses' => 'LeaveAgentController@download']);

			Route::get('/create', ['as' => 'leave_agent_create', 'uses' => 'LeaveAgentController@create']);
			Route::post('/store', ['as' => 'leave_agent_store', 'uses' => 'LeaveAgentController@store']);

			/*Route::get('/add-leave-date', ['as' => 'leave_agent_add_date', 'uses' => 'LeaveAgentController@add_leave_dates']);
			Route::get('/show-leave-dates', ['as' => 'leave_agent_show_dates', 'uses' => 'LeaveAgentController@show_leave_dates']);*/
		});# Agent
	});# Leave
	
	# Materfile
	Route::group(['prefix' => 'masterfile'], function(){
		Route::get('/', ['as' => 'masterfile_index', 'uses' => 'MasterfileController@index']);
		Route::get('/profile/{id}', ['as' => 'masterfile_profile', 'uses' => 'MasterfileController@profile']);

		Route::get('/create', ['as' => 'masterfile_create', 'uses' => 'MasterfileController@create']);
		Route::post('/store', ['as' => 'masterfile_store', 'uses' => 'MasterfileController@store']);

		Route::get('/edit/{id}', ['as' => 'masterfile_edit', 'uses' => 'MasterfileController@edit']);
		Route::post('/update/{id}', ['as' => 'masterfile_update', 'uses' => 'MasterfileController@update']);

		Route::get('/separation/{id}', ['as' => 'masterfile_separation_create', 'uses' => 'MasterfileController@separation_create']);
		Route::post('/separation-store/{id}', ['as' => 'masterfile_separation_store', 'uses' => 'MasterfileController@separation_store']);

		Route::get('/separation-edit/{id}', ['as' => 'masterfile_separation_edit', 'uses' => 'MasterfileController@separation_edit']);
		Route::post('/separation-update/{id}', ['as' => 'masterfile_separation_update', 'uses' => 'MasterfileController@separation_update']);

		Route::get('/positions/{depID?}', ['as' => 'masterfile_poistions_url', 'uses' => 'MasterfileController@positions']);

	});# Materfile
	
	# Ezwatcher
	Route::group(['prefix' => 'timekeeping'], function(){
		Route::get('ezwatch', ['as' => 'ezwatch', 'uses' => 'TimeKeepingController@ezwatch']);
		Route::get('doorlog', ['as' => 'doorlog', 'uses' => 'TimeKeepingController@doorlog']);

		Route::get('search/employee', ['as' => 'ez_search_employee', 'uses' => 'TimeKeepingController@ezsearchemployee']);
		
		Route::get('ezwatch/generate', ['as' => 'ez_search_lilo_generate', 'uses' => 'TimeKeepingController@ezsearchlilogenerate']);
		Route::get('ezwatch/download', ['as' => 'ez_search_lilo_download', 'uses' => 'TimeKeepingController@ezsearchlilodownload']);
		Route::get('ezwatch/preview', ['as' => 'ez_search_lilo_preview', 'uses' => 'TimeKeepingController@ezsearchlilopreview']);
		Route::get('ezwatch/preview/archive', ['as' => 'ez_preview_archive', 'uses' => 'TimeKeepingController@archivepreview']);
		Route::get('ezwatch/preview/transaction', ['as' => 'ez_preview_transaction', 'uses' => 'TimeKeepingController@transactionpreview']);
	});

	# Network Utilization
	Route::group(['prefix' => 'network-utilization'], function(){
		Route::get('/', ['as' => '/', 'uses' => 'NetworkUtilizationController@index']);
		Route::get('upload', ['as' => 'upload', 'uses' => 'NetworkUtilizationController@upload']);
	});

	# Seat Plan Project
	Route::group(['prefix' => 'seatplan'], function(){
		Route::get('control', ['as' => 'seatplan_control', 'uses' => 'SeatPlanController@index']);
		Route::get('bu', ['as' => 'seatplan_bu', 'uses' => 'SeatPlanController@index']);
		Route::get('team', ['as' => 'seatplan_team', 'uses' => 'SeatPlanController@index']);
	});
	
	#	Agent Metrics
	Route::group(['prefix' => 'metrics'], function(){
		Route::get('metrics/{id?}', ['as' => 'metrics', 'uses' => 'MetricsController@showMetric']);
	});

	#	Agent Release Call Log
	Route::group(['prefix' => 'release-call-log'], function(){
		Route::get('/', ['as' => 'release_call_log', 'uses' => 'ReleaseCallLogController@index']);
		Route::post('release-call-store', ['as' => 'release_call_store', 'uses' => 'ReleaseCallLogController@store']);
		Route::get('reports-CMS', ['as' => 'reports_CMS', 'uses' => 'ReleaseCallLogController@rptCMS']);
		Route::get('download-CMS', ['as' => 'download_CMS', 'uses' => 'ReleaseCallLogController@dlcms']);
		Route::get('reports-supervisor', ['as' => 'reports_supervisor', 'uses' => 'ReleaseCallLogController@rptsupervisor']);
		Route::get('generate-report', ['as' => 'generate_report', 'uses' => 'ReleaseCallLogController@generatereport']);
		Route::get('download-supervisor', ['as' => 'download_supervisor', 'uses' => 'ReleaseCallLogController@dlsupervisor']);
	});
	
	# Activity Log
	Route::group(['prefix' => 'activity-logger'], function(){
		Route::get('/', ['as' => 'supervisor_logger', 'uses' => 'SupervisorActivityLoggerController@index']);
	});

	# Admin Configuration
	Route::group(['prefix' => 'cpanel'], function(){
		# main cpanel
		Route::get('/', ['as' => 'cpanel_index', 'uses' => 'ConfigurationsController@index']);
		#	Users
		Route::group(['prefix' => 'users'], function(){
			Route::get('/', ['as' => 'users_index', 'uses' => 'UsersController@index']);
			Route::get('/edit/{ntlogin}', ['as' => 'users_edit', 'uses' => 'UsersController@edit']);
			Route::post('/update/{ntlogin}', ['as' => 'users_update', 'uses' => 'UsersController@update']);
			Route::get('/search', ['as' => 'users_search_json', 'uses' => 'UsersController@search_json']);
			#	Special Permission

app/LeaveAgent.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Users;

class LeaveAgent extends Model
{
    public $table = 'leave_agent';
    public $timestamps = false;

    /**
    Setters
    **/
    public function setLeaveDateAttribute($value)
	{
     	$this->attributes['leave_date'] = date('Y-m-d', strtotime($value));
	}


    /**
    Getters
    **/
    public function getLeaveDateFormatAttribute()
	{
     	return date('D, F d, Y', strtotime($this->leave_date));
	}

    public function getEmployeeNumberAttribute()
	{
		$ntlogin 	= $this->ntlogin;
		$employee 	= Users::where('ntlogin', $ntlogin)->first();

     	return $employee->employee_number;
	}

    public function getEmployeeNameAttribute()
	{
		$ntlogin 	= $this->ntlogin;
		$employee 	= Users::where('ntlogin', $ntlogin)->first();

     	return $employee->name;
	}
}

resources/views/push/leave/agent/agent_filed_leaves.blade.php
@extends('push.layout.master')

@section('container')
@parent
<!-- Starts -->

  <div class="row">
    <div class="large-12 columns">
      <h4><i class="fa fa-sign-in"></i> Download Agent Filed Leave</h4>
    </div>
  </div><!-- row -->

  <form action="{{ $action }}" method="post" >
    <div class="row">

      <div class="large-6 columns">

          <div class="row">
            <div class="large-12 columns">
              <label for="reason" class="">Reason:</label>
              <input type="text" name="leave_date" id="leave_date" placeholder="Date" data-date-format="%m/%d/%Y" data-date />
            </div>
          </div>

          <div class="row">
            <div class="large-9 columns">
              {!! csrf_field() !!}
              <button type="submit" class="button">Download</button>
            </div>
            <div class="large-3 columns">&nbsp;</div>
          </div>
      </div><!-- large-6 columns -->

    </div><!-- row -->
  </form>

<!-- Stops -->
@stop

resources/views/push/leave/agent/create.blade.php
@extends('push.layout.master')

@section('container')
@parent
<!-- Starts -->

  <div class="row">
    <div class="large-12 columns">
      <h4><i class="fa fa-sign-in"></i> My Leave</h4>
    </div>
  </div><!-- row -->

  <form action="{{ $action }}" method="post">
    @include('push.messages.error_message_list')
    @include('push.messages.success_message')
    <div class="row">

      <div class="large-6 columns">
          <div class="row">
            <div class="large-12 columns">
              <label for="leave_type" class="">Type of Leave:</label>
              <select name="leave_type" id="leave_type">
                <option value="">-- Select --</option>
                @foreach($leave_types as $row)
                  <option value="{{ $row }}">{{ $row }}</option>
                @endforeach
              </select>
            </div>
          </div>

          <div class="row">
            <div class="large-12 columns">
              <label for="reason" class="">Reason:</label>
              <textarea rows="5" name="reason" id="reason">{{ $reason }}</textarea>
            </div>
          </div>

          <div class="row">
            <div class="large-9 columns">
              <button type="submit" class="button">Submit</button>
              <a class="button secondary" href="{{ route('leave_agent_index') }}">Back</a>
            </div>
            <div class="large-3 columns">&nbsp;</div>
          </div>
      </div><!-- large-6 columns -->

      <div class="large-6 columns">
        <label for="leave_date" class="">Date (<i>EST</i>):</label>
        <input type="hidden" name="leave_agent_add_date_url" id="leave_agent_add_date_url" value="{{ route('leave_agent_add_date') }}" />
        <input type="hidden" name="leave_agent_show_dates_url" id="leave_agent_show_dates_url" value="{{ route('leave_agent_show_dates') }}" />
        <input type="text" name="leave_date" id="leave_date" placeholder="Date" data-date-format="%Y-%m-%d" data-date />
        <input type="hidden" name="click_count" id="click_count" value="0" />
        {!! csrf_field() !!}
        <br />
        <table class="leave_dates" width="100%">
          <thead>
            <tr>
              <td width="10%"></td>
              <td width="90%">Date/s</td>
            </tr>
          </thead>
          <tbody></tbody>
        </table>
      </div><!-- large-6 columns -->

    </div><!-- row -->
  </form>
<script type="text/javascript">
<?php

echo '$(\'#leave_type\').val(\'' . $leave_type . '\');';

if(count($leave_dates) - 1 > 0)
{
  echo '$(\'#click_count\').val(\'' . (count($leave_dates) - 1) . '\');';

  $count = 0;
  foreach ($leave_dates as $date)
  {
    $button = '<a href="#" onclick="remove_date(\\\'row_' . $count . '\\\')"><i class="fa fa-times fa-lg"></i></a>';
    $input  = '<input type="hidden" class="leave_dates_list" name="leave_dates[' . $count . ']"  value="' . $date . '" />';
    $row    = '<tr class="row_' . $count . '"><td>' . $button . '</td><td>' . $date . '' . $input . '</td></tr>';

    echo '$(\'table.leave_dates tbody\').append(\'' . $row . '\');';

    $count++;
  }
}
/*if(Session::has('user.leave'))
{
  echo 'leave_dates();';
}*/
?>
var xhr_leave_agent_add_date = null;

$(function(){
  $('.date-picker').click(function(e){
    var date_count = parseInt($('#click_count').val());
    var add_cond = true;
    var date = $('.calendar .selector ,value').text();
    var input_count = $('.leave_dates_list').size();
    var button = '<a href="#" onclick="remove_date(\'row_' + date_count + '\')"><i class="fa fa-times fa-lg"></i></a>';
    var date_now = new Date('<?php echo date('Y-m-d'); ?>');
    var selected_date = new Date(date);

    //console.log(selected_date.getTime() >= date_now.getTime());
    //console.log(date_now.getTime() >= selected_date.getTime());
    //console.log(date_now.getTime() + ' ' + selected_date.getTime());

    if(input_count != 0)
    {
      $('.leave_dates_list').each(function(){
        //console.log($(this).val() + ' = ' + date);
        if($(this).val() == date)
        {
          input_count++;
          add_cond = false;
          return false;
        }
      });
    }

    var input = '<input type="hidden" class="leave_dates_list" name="leave_dates[' + date_count + ']"  value="' + date + '" />';
    var row = '<tr class="row_' + date_count + '"><td>' + button + '</td><td>' + date + '' + input + '</td></tr>';

    if(add_cond)
    {
      $('table.leave_dates tbody').append(row);
    }
    
    $('#click_count').val((date_count+1));
    
    e.preventDefault();
    //console.log(date);
    /*xhr_leave_agent_add_date = $.ajax({
        type : 'get',
        url : $("#leave_agent_add_date_url").val(),
        data : 'date=' + date,
        cache : false,
        dataType : "script",
        beforeSend: function(xhr){
            if (xhr_leave_agent_add_date != null)
            {
                xhr_leave_agent_add_date.abort();
            }
        }
    }).done(function(data){
      //
    }).fail(function(jqXHR, textStatus){
      //console.log('Request failed: ' + textStatus);
    });*/
  });
});

var xhr_leave_agent_show_dates = null;
function leave_dates()
{
  xhr_leave_agent_show_dates = $.ajax({
      type : 'get',
      url : $("#leave_agent_show_dates_url").val(),
      cache : false,
      dataType : "json",
      beforeSend: function(xhr){
          if (xhr_leave_agent_show_dates != null)
          {
              xhr_leave_agent_show_dates.abort();
          }
      }
  }).done(function(data){
    //
    console.log(data);
  }).fail(function(jqXHR, textStatus){
    //console.log('Request failed: ' + textStatus);
  });
}

function remove_date(row)
{
  $('.' + row).remove();
  return false;
}
</script>
<!-- Stops -->
@stop

resources/views/push/leave/agent/index.blade.php
@extends('push.layout.master')

@section('container')
@parent
<!-- Starts -->

  <div class="row">
    <div class="large-12 columns">
      <h4><i class="fa fa-sign-in"></i> My Leave</h4>
    </div>
  </div><!-- row -->

  <div class="row">
    <div class="large-12 columns">
      <a href="{{ route('leave_agent_create') }}" class="button"><i class="fa fa-plus"></i> File a Leave</a>
    </div>
  </div><!-- row -->

  <div class="row">
    <div class="large-12 columns">
      {!! str_replace('/?', '?', $leaves->render()) !!}
      <table width="100%">
        <thead>
          <tr>
            <th width="25%">Leave Type</th>
            <th width="25%">Leave Date</th>
            <th width="50%">Reason</th>
          </tr>
        </thead>
        <tbody>
          @foreach($leaves as $row)
          <tr>
            <td>{{ $row->leave_type }}</td>
            <td>{{ $row->leave_date_format }} <i>EST</i></td>
            <td>{{ $row->reason }}</td>
          </tr>
          @endforeach
        </tbody>
      </table>
      {!! str_replace('/?', '?', $leaves->render()) !!}
    </div>
  </div><!-- row -->

<!-- Stops -->
@stop