app/Http/routes.php
			Route::get('/create', ['as' => 'leave_agent_create', 'uses' => 'LeaveAgentController@create']);
			Route::post('/store', ['as' => 'leave_agent_store', 'uses' => 'LeaveAgentController@store']);

			/*Route::get('/add-leave-date', ['as' => 'leave_agent_add_date', 'uses' => 'LeaveAgentController@add_leave_dates']);
			Route::get('/show-leave-dates', ['as' => 'leave_agent_show_dates', 'uses' => 'LeaveAgentController@show_leave_dates']);*/
		});# Agent
	});# Leave
	
	# Materfile
	Route::group(['prefix' => 'masterfile'], function(){
		Route::get('/', ['as' => 'masterfile_index', 'uses' => 'MasterfileController@index']);
		Route::get('/profile/{id}', ['as' => 'masterfile_profile', 'uses' => 'MasterfileController@profile']);

		Route::get('/create', ['as' => 'masterfile_create', 'uses' => 'MasterfileController@create']);
		Route::post('/store', ['as' => 'masterfile_store', 'uses' => 'MasterfileController@store']);

		Route::get('/edit/{id}', ['as' => 'masterfile_edit', 'uses' => 'MasterfileController@edit']);
		Route::post('/update/{id}', ['as' => 'masterfile_update', 'uses' => 'MasterfileController@update']);

		Route::get('/separation/{id}', ['as' => 'masterfile_separation_create', 'uses' => 'MasterfileController@separation_create']);
		Route::post('/separation-store/{id}', ['as' => 'masterfile_separation_store', 'uses' => 'MasterfileController@separation_store']);

		Route::get('/separation-edit/{id}', ['as' => 'masterfile_separation_edit', 'uses' => 'MasterfileController@separation_edit']);
		Route::post('/separation-update/{id}', ['as' => 'masterfile_separation_update', 'uses' => 'MasterfileController@separation_update']);

		Route::get('/positions/{depID?}', ['as' => 'masterfile_poistions_url', 'uses' => 'MasterfileController@positions']);

	});# Materfile
	
	# Ezwatcher
	Route::group(['prefix' => 'timekeeping'], function(){
		Route::get('ezwatch', ['as' => 'ezwatch', 'uses' => 'TimeKeepingController@ezwatch']);
		Route::get('doorlog', ['as' => 'doorlog', 'uses' => 'TimeKeepingController@doorlog']);

		Route::get('search/employee', ['as' => 'ez_search_employee', 'uses' => 'TimeKeepingController@ezsearchemployee']);
		
		Route::get('ezwatch/generate', ['as' => 'ez_search_lilo_generate', 'uses' => 'TimeKeepingController@ezsearchlilogenerate']);
		Route::get('ezwatch/download', ['as' => 'ez_search_lilo_download', 'uses' => 'TimeKeepingController@ezsearchlilodownload']);
		Route::get('ezwatch/preview', ['as' => 'ez_search_lilo_preview', 'uses' => 'TimeKeepingController@ezsearchlilopreview']);
		Route::get('ezwatch/preview/archive', ['as' => 'ez_preview_archive', 'uses' => 'TimeKeepingController@archivepreview']);
		Route::get('ezwatch/preview/transaction', ['as' => 'ez_preview_transaction', 'uses' => 'TimeKeepingController@transactionpreview']);
	});

	# Network Utilization
	Route::group(['prefix' => 'network-utilization'], function(){
		Route::get('/', ['as' => '/', 'uses' => 'NetworkUtilizationController@index']);
		Route::get('upload', ['as' => 'upload', 'uses' => 'NetworkUtilizationController@upload']);
	});

	# Seat Plan Project
	Route::group(['prefix' => 'seatplan'], function(){
		Route::get('control', ['as' => 'seatplan_control', 'uses' => 'SeatPlanController@index']);
		Route::get('bu', ['as' => 'seatplan_bu', 'uses' => 'SeatPlanController@index']);
		Route::get('team', ['as' => 'seatplan_team', 'uses' => 'SeatPlanController@index']);
	});
	
	#	Agent Metrics
	Route::group(['prefix' => 'metrics'], function(){
		Route::get('metrics/{id?}', ['as' => 'metrics', 'uses' => 'MetricsController@showMetric']);
	});

	#	Agent Release Call Log
	Route::group(['prefix' => 'release-call-log'], function(){
		Route::get('/', ['as' => 'release_call_log', 'uses' => 'ReleaseCallLogController@index']);
		Route::post('release-call-store', ['as' => 'release_call_store', 'uses' => 'ReleaseCallLogController@store']);
		Route::get('reports-CMS', ['as' => 'reports_CMS', 'uses' => 'ReleaseCallLogController@rptCMS']);
		Route::get('download-CMS', ['as' => 'download_CMS', 'uses' => 'ReleaseCallLogController@dlcms']);
		Route::get('reports-supervisor', ['as' => 'reports_supervisor', 'uses' => 'ReleaseCallLogController@rptsupervisor']);
		Route::get('generate-report', ['as' => 'generate_report', 'uses' => 'ReleaseCallLogController@generatereport']);
		Route::get('download-supervisor', ['as' => 'download_supervisor', 'uses' => 'ReleaseCallLogController@dlsupervisor']);
	});
	
	# Activity Log
	Route::group(['prefix' => 'activity-logger'], function(){
		Route::get('/', ['as' => 'supervisor_logger', 'uses' => 'SupervisorActivityLoggerController@index']);
	});

	# Admin Configuration
	Route::group(['prefix' => 'cpanel'], function(){
		# main cpanel
		Route::get('/', ['as' => 'cpanel_index', 'uses' => 'ConfigurationsController@index']);
		#	Users
		Route::group(['prefix' => 'users'], function(){
			Route::get('/', ['as' => 'users_index', 'uses' => 'UsersController@index']);
			Route::get('/edit/{ntlogin}', ['as' => 'users_edit', 'uses' => 'UsersController@edit']);
			Route::post('/update/{ntlogin}', ['as' => 'users_update', 'uses' => 'UsersController@update']);
			Route::get('/search', ['as' => 'users_search_json', 'uses' => 'UsersController@search_json']);
			#	Special Permission
			Route::group(['prefix' => 'special'], function(){
				Route::get('', ['as' => 'users_special', 'uses' => 'UsersSpecialPermissionController@index']);
				Route::get('add', ['as' => 'users_special_add', 'uses' => 'UsersSpecialPermissionController@add']);
				Route::post('store', ['as' => 'users_special_store', 'uses' => 'UsersSpecialPermissionController@store']);
				Route::get('destroy/{ntlogin}', ['as' => 'users_special_destroy', 'uses' => 'UsersSpecialPermissionController@destroy']);
			});
			#	Admin
			Route::group(['prefix' => 'admin'], function(){
				Route::get('', ['as' => 'users_admin', 'uses' => 'UsersAdminController@index']);
				Route::get('add', ['as' => 'users_admin_add', 'uses' => 'UsersAdminController@add']);
				Route::post('store', ['as' => 'users_admin_store', 'uses' => 'UsersAdminController@store']);
				Route::get('destroy/{ntlogin}', ['as' => 'users_admin_destroy', 'uses' => 'UsersAdminController@destroy']);
			});
			# Conversation
			Route::group(['prefix' => 'conversation'], function(){
				Route::get('/', ['as' => 'conversation_index', 'uses' => 'UserConversationController@index']);
				Route::get('create', ['as' => 'conversation_create', 'uses' => 'UserConversationController@create']);
				Route::post('store', ['as' => 'conversation_store', 'uses' => 'UserConversationController@store']);
				Route::get('destroy/{ntlogin}', ['as' => 'conversation_destroy', 'uses' => 'UserConversationController@destroy']);
			});
			# Distribution
			Route::group(['prefix' => 'distribution'], function(){
				Route::get('/', ['as' => 'user_distribution_index', 'uses' => 'UserDistributionController@index']);
				Route::get('create', ['as' => 'user_distribution_create', 'uses' => 'UserDistributionController@create']);
				Route::post('store', ['as' => 'user_distribution_store', 'uses' => 'UserDistributionController@store']);
				Route::get('destroy/{ntlogin}/{distribution_id}', ['as' => 'user_distribution_destroy', 'uses' => 'UserDistributionController@destroy']);
			});
			# Announcement
			Route::group(['prefix' => 'announcement'], function(){
				Route::get('/', ['as' => 'announcement_index', 'uses' => 'UserAnnouncementController@index']);
				Route::get('create', ['as' => 'announcement_create', 'uses' => 'UserAnnouncementController@create']);
				Route::post('store', ['as' => 'announcement_store', 'uses' => 'UserAnnouncementController@store']);
				Route::get('destroy/{ntlogin}', ['as' => 'announcement_destroy', 'uses' => 'UserAnnouncementController@destroy']);
				Route::get('show', ['as' => 'announcement_show', 'uses' => 'UserAnnouncementController@show']);
				Route::get('update/{id}/{active}', ['as' => 'announcement_update', 'uses' => 'UserAnnouncementController@update']);
			});
			# Roster
			Route::group(['prefix' => 'roster'], function(){
				Route::get('/', ['as' => 'roster_index', 'uses' => 'RosterController@show']);
			});
		});

		# Uploads
		Route::group(['prefix' => 'uploads'], function(){
			# File Uploads
			Route::get('file-uploads', ['as' => 'file_uploads', 'uses' => 'FileUploadsController@index']);
			Route::post('file-uploads-store', ['as' => 'file_uploads_store', 'uses' => 'FileUploadsController@store']);
			Route::get('file-uploads-delete/{id}', ['as' => 'file_uploads_delete', 'uses' => 'FileUploadsController@delete']);
			# Agent Break Schedule
			Route::get('upload-agent-break-schedules', ['as' => 'upload_agent_break_schedules', 'uses' => 'AgentBreakSchedulesController@index']);
			Route::post('upload-agent-break-schedules-store', ['as' => 'upload_agent_schedules_break_store', 'uses' => 'AgentBreakSchedulesController@store']);
			# Call Center Roster
			Route::get('upload-roster', ['as' => 'upload_roster', 'uses' => 'RosterController@index']);
			Route::post('upload-roster-store', ['as' => 'upload_roster_store', 'uses' => 'RosterController@store']);
		});

		# distributions
		Route::group(['prefix' => 'distribution'], function(){
			Route::get('/', ['as' => 'distribution_index', 'uses' => 'DistributionsController@index']);
			Route::get('create', ['as' => 'distribution_create', 'uses' => 'DistributionsController@create']);
			Route::get('edit/{id}', ['as' => 'distribution_edit', 'uses' => 'DistributionsController@edit']);
			Route::post('store', ['as' => 'distribution_store', 'uses' => 'DistributionsController@store']);
			Route::post('update', ['as' => 'distribution_update', 'uses' => 'DistributionsController@update']);

		});

		# Configuration
		Route::group(['prefix' => 'cpanel', 'middleware' => 'auth'], function(){
			# main cpanel
			Route::get('/', ['as' => 'cpanel_index', 'uses' => 'ConfigurationsController@index']);

			# distributions
			Route::group(['prefix' => 'distribution'], function(){

app/Masterfile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\MasterfileEmployeeAccount;
use App\MasterfileEmployeeInformation;
use App\MasterfileDepartments;
use \Carbon\Carbon;

class Masterfile extends Model
{
    protected $connection = 'mysql2';
    protected $table = 'employee';
    public $timestamps = false;

    /**
    Some Functions
    **/
    public function getEmployeeNumberAttribute()
    {
		$id 		= $this->empID;
		$employee 	= MasterfileEmployeeAccount::where('empID', $id)->first();

     	return $employee->empNumber;
    }

    public function getDepartmentNameAttribute()
    {
		$id 	= $this->empID;
		$info 	= MasterfileEmployeeInformation::where('empID', $id)->first();

		if($info->department == 0)
		{
			return '';
		}

		$row 	= MasterfileDepartments::where('depID', $info->department)->first();
	    
	    return $row->department;
    }

    public function getEmployeeFullNameAttribute()
    {
        return $this->firstName . ' ' . $this->middleName . ' ' . $this->lastName . ' ' . $this->suffix;
    }

    public function getBirthDateFormatAttribute()
    {
        return date('F d, Y', strtotime($this->birthDate));
    }

    public function getGenderFormatAttribute()
    {
        return ($this->gender == 0)? 'Male' : 'Female';
    }

    public function getCivilStatusFormatAttribute()
    {
        $value = $this->civil_status;
        if($value == 1)
        {
            return 'Single';
        }
        elseif($value == 2)
        {
            return 'Married';
        }
        elseif($value == 3)
        {
            return 'Widowed';
        }
        elseif($value == 4)
        {
            return 'Divorced';
        }
    }
}

app/Http/Controllers/MetricsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Validator;

class MetricsController extends Controller
{

    public function showMetric($id = "")
    {
        //
        
        return view('push.metrics/metrics', ['specMetric' => $id]);
    }
}

resources/views/push/metrics/metrics.blade.php
@extends('push.layout.master')

@section('container')
@parent
<!-- Starts -->

	<!--{{ Auth::user()->employee_number }}-->

	<!-- Container Title -->
	<div class="row">
	  <div class="medium-12 columns">
		<div class="row">
			<div class="medium-12 columns">
				<dl class="sub-nav">
					<dt><i class="fa fa-line-chart"></i> {{$specMetric}}</dt>
				</dl>
			</div>
		</div>
		<!-- Tabs -->
	  </div>
	</div>
	<!-- Container Title -->

	<div class="row">
		<div class="medium-5 columns">
			{{-- Form --}}
			<form id="metricForm">
				<fieldset>
    			<legend>2015 PB Calendar - Fourth Quarter</legend>
    			<input type="hidden" id="metric" value="{{ $specMetric }}">
					{{-- Month --}}
				<div class="row">
					<div class="medium-7 columns">
					  <select id="metric_mm" name="metric_mm">
					    <option value = "1">January</option>
                        <option value = "2">February</option>
                        <option value = "3">March</option>
                        <option value = "4">April</option>
                        <option value = "5">May</option>
                        <option value = "6">June</option>
                        <option value = "7">July</option>
                        <option value = "8">August</option>
                        <option value = "9">September</option>
                        <option value = "10">October</option>
                        <option value = "11">November</option>
                        <option value = "12">December</option>
					  </select>
					</div>
					{{-- Month --}}

					{{-- WE --}}
					<div class="medium-5 columns" id="weekEndings">
					  <select id="metric_we" name="metric_we">
                        <option value = "15">15</option>
                        <option value = "30">30</option>
					  </select>
					</div>
					{{-- WE --}}
            </form>
            {{-- Form --}}
            </div>
            <div class="row">
	            <div class="large-12 columns">
				  <ul class="button-group small expand radius toggle" data-toggle="buttons-radio" style="text-align: center;">
					<li style="display: inline-block;">
						<input type="radio" id="r1" name="r-group" data-toggle="button">
						<label class="button" for="r1">Week 1</label>
					</li>
					<li style="display: inline-block;">
						<input type="radio" id="r2" name="r-group" data-toggle="button">
						<label class="button" for="r2">Week 2</label>
					</li>
					<li style="display: inline-block;">
						<input type="radio" id="r3" name="r-group" data-toggle="button">
						<label class="button" for="r3">Week 3</label>
					</li>
				  </ul>
				</div>
			</div>
        </div>

		<div class="medium-7 columns condensed-table">
			<table>
																<tr><th></th>		<th>Target</th>		<th>Weight</th>
																	<th></th>		<th>Target</th>		<th>Weight</th></tr>
				<tr><th style="background-color: #EEEEEE;" width="10%">QA</th>		<td>92.0%</td>		<td style="font-weight:bold;">00.00</td>
					<th style="background-color: #EEEEEE;" width="10%">Transfer</th><td>20.0%</td>		<td style="font-weight:bold;">00.00</td>
				<tr><th style="background-color: #EEEEEE;" width="10%">SchedAd</th>	<td>90.0%</td>		<td style="font-weight:bold;">00.00</td>
					<th style="background-color: #EEEEEE;" width="10%">ORI</th>		<td>100.0%</td>		<td style="font-weight:bold;">00.00</td></tr>
				<tr><th style="background-color: #EEEEEE;" width="10%">Attendance</th><td>00.00</td>	<td style="font-weight:bold;">00.00</td>
					<th style="background-color: #EEEEEE;" width="10%">SCORE</th>	<td colspan="2" style="font-weight:bold;">100.00</td></tr>
			</table>
		</div>
	</div>

	<div class="row">
		<!-- Tab Content -->
		<div class="medium-12 columns">
			  <div class="" id="weekly">
			    <table id="weeklyTab" width="100%">
					<thead>
						<tr>
						  <th class="centerHeader" rowspan="2"></th>
						  <th class="centerHeader" rowspan="2">MON</th>
						  <th class="centerHeader" rowspan="2">TUE</th>
						  <th class="centerHeader" rowspan="2">WED</th>
						  <th class="centerHeader" rowspan="2">THUR</th>
						  <th class="centerHeader" rowspan="2">FRI</th>
						  <th class="centerHeader" rowspan="2">SAT</th>
						  <th class="centerHeader" rowspan="2">SUN</th>
						  <th class="centerHeader" colspan="3">WTD</th>
						</tr>
						<tr>
						  <th class="centerHeader">Orig</th>
						  <th class="centerHeader">Score</th>
						  <th class="centerHeader">Pts</th>
						</tr>
					</thead>
					<tbody>
						<tr>
						  <th style="text-align: left;">QA</th>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						</tr>

						<tr>
						  <th style="text-align: left;">Transfer Rate</th>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						</tr>

						<tr>
						  <th style="text-align: left;">Schedule Adherence</th>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						</tr>

						<tr>
						  <th style="text-align: left;">Attendance</th>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						</tr>

						<tr>
						  <th style="text-align: left;">ORI</th>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						  <td style="text-align: center;">00.00</td>
						</tr>
					</tbody>
				<tbody id="body_weekly" class="metricTableBody" ></tbody>
				</table>
			  </div>
		</div>
		<!-- Tab Content -->

<!-- Stops -->
@stop

@section('scripts')
  @include('push.scripts.metrics_js')
@stop